### PR TITLE
Fixed required library download (link is now up-to-date)

### PR DESCRIPTION
**Pull request by RFlintstone**
Fixed my own issue https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/issues/100

### CODE REVIEW

**Comment by TheCommieAxolotl** [comment]
Closed in favour of 38b22daa8db787b24a60730e51cfd0f757949704

**Comment by RFlintstone** [comment]
> Closed in favour of [38b22da](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/38b22daa8db787b24a60730e51cfd0f757949704)

Those are literally the same changes. Please elaborate on why this PR is denied. 
_Also_ if you want to use SemVer properly it should be *at least* a minor update as without this change the plugins break. 
A patch is a small bug fix which doesn't force you to update to a new version.

image
https://semver.org/

**Comment by TheCommieAxolotl** [comment]
You included metadata files such as `.idea/*` in the pr, as well as incorrectly bumping versions & updating changelogs (both of which I generally don't accept in prs)

It was less effort for me to make a similar commit than coach this pr to slim down into what should be a simple change.

As the image you provided mentioned, minor versions are for *adding* functionality.

**Comment by RFlintstone** [comment]
> It was less effort for me to make a similar commit than coach this pr to slim down into what should be a simple change.

Fair enough, I updated the version + changelog so it would be less work on your end. I was not aware that this is something you generally don't accept.

**Pull request closed without merging**
